version: '3'
services:
    jenkins:
        image: "jenkins/jenkins:lts"
        container_name: "factoryJenkins"
        hostname: "factoryjenkins"
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins_home:/var/jenkins_home
        environment:
            myVar: "valoare"
volumes:
    jenkins_home:
         external:
            name: jenkins_home
